[CRC35.3]
name = JSTOM Colon local
expr= database/jstom-expr.txt
index= database/jstom-idx.txt
survival= database/jstom-survival.txt
indexHeader= database/jstom-ih.txt
info= database/jstom-info.txt
key= mac:
source= GSE13067,GSE14333,GSE17538,GSE31595,GSE37892,GSE33113

[LIV15.2]
name = Hoshida 2013 Cir RMA local
expr= database/chronic-liver-expr.txt
index= database/chronic-liver-idx.txt
survival= database/chronic-liver-survival.txt
indexHeader= database/chronic-liver-ih.txt
info= database/chronic-liver-info.txt
key= mac:
source= GSE15654

[MAC104]
name = Scicluna 2015 Sepsis blood local
expr= database/sepsis-expr.txt
index= database/sepsis-idx.txt
survival= database/sepsis-survival.txt
indexHeader= database/sepsis-ih.txt
info= database/sepsis-info.txt
key= mac:
source= GSE65682

[MACV74]
name = Herazo-Maya 2013 IPF I local
expr= database/ipf-1-expr.txt
index= database/ipf-1-idx.txt
survival= database/ipf-1-survival.txt
indexHeader= database/ipf-1-ih.txt
info= database/ipf-1-info.txt
key= mac:
source= GSE28221

[MACV75]
name = Herazo-Maya 2013 IPF II local
expr= database/ipf-2-expr.txt
index= database/ipf-2-idx.txt
survival= database/ipf-2-survival.txt
indexHeader= database/ipf-2-ih.txt
info= database/ipf-2-info.txt
key= mac:
source= GSE28221

[MACV82]
name = Einecke 2010 kidney transplant local
expr= database/kidney-transplant-tissue-expr.txt
index= database/kidney-transplant-tissue-idx.txt
survival= database/kidney-transplant-tissue-survival.txt
indexHeader= database/kidney-transplant-tissue-ih.txt
info= database/kidney-transplant-tissue-info.txt
key= mac:
source= GSE21374

[MACV80]
name = Zhang 2019 kidney transplant blood local
expr= database/kidney-transplant-blood-expr.txt
index= database/kidney-transplant-blood-idx.txt
survival= database/kidney-transplant-blood-survival.txt
indexHeader= database/kidney-transplant-blood-ih.txt
info= database/kidney-transplant-blood-info.txt
key= mac:
source= GSE112927

[MACV120.2]
name = Kuparinen 2013 outcome local
expr= database/aging-expr.txt
index= database/aging-idx.txt
survival= database/aging-survival.txt
indexHeader= database/aging-ih.txt
info= database/aging-info.txt
key= mac:
source= GSE65218

