#!/bin/bash

export JAVA_HOME="/booleanfs/sahoo/softwares/java/jdk1.8.0_45"
export PATH=$JAVA_HOME/bin:$PATH
export CLASSPATH="./stepminer-1.1.jar"
stepminer="java -cp $CLASSPATH -Xms64m -Xmx10G tools.CustomAnalysis"
stepminer1="java -cp $CLASSPATH -Xms64m -Xmx10G tools.Analyze"
export PERL_HASH_SEED=0

perl -I.. ../analyze.pl data-download COV323 Ham-namir
perl -I.. ../analyze.pl toidx Ham-namir-expr.txt > Ham-namir-idx.txt

for i in Ham-namir-expr.txt
do
    P=${i/-expr.txt/}
    echo $P
    rm -f "$P-thr.txt" "$P-info.txt" "$P-vinfo.txt" "$P-bv.txt"
    if [[ ! -f "$P-thr.txt" ]]; then
      perl -I.. ../analyze.pl thr $i 2 70000 0.5 > "$P-thr.txt"
    fi
    if [[ ! -f "$P-info.txt" ]]; then
      perl -I.. ../analyze.pl Info  $P > $P-info.txt
    fi
    if [[ ! -f "$P-vinfo.txt" ]]; then
      perl -I.. ../analyze.pl VInfo $P > $P-vinfo.txt
    fi
    if [[ ! -f "$P-bv.txt" ]]; then
      perl -I.. ../analyze.pl bv $P > $P-bv.txt
    fi
done

python3 process.py

